Submission of dismo, dsmextra, MinBAR and rgbif
sylvainschmitt/sdmverse pull request #19
Opened 2023-05-02 09:11 UTC by sylvainschmitt

This is the submission of dismo, dsmextra, MinBAR and rgbif as the authors are not authors of the manuscript in preparation. I also added a new function `template_from_cran` to help build a submission in R. As I am not the author of these packages, I will not detail the features, as I would prefer the reviewers to check the original documentation to see if I am not wrong.

2023-05-02 09:12 UTC, sylvainschmitt commented
I'm looking for reviewers: @EduardoArle , @gepinillab , @hannahlowens , @jamiemkass , @sgvignali, @codelab3 , @adamlilith; @MayaGueguen are you available? Please have a look at the [reviewing guidelines](https://github.com/sylvainschmitt/sdmverse/blob/main/REVIEWING.md)

2023-05-10 07:23 UTC, jamiemkass commented
I can review here.

2023-05-11 07:07 UTC, jamiemkass commented on R/template_from_cran.R
> +  if(!is.null(path))
Would be better to rewrite this as an if/else.

2023-05-11 07:28 UTC, sylvainschmitt commented
@jamiemkass , as discussed I removed dsmextra and MinBAR. And I followed your suggestion for the template_from_cran function. I'm waiting for your review of the fields to merge the PR.

2023-05-11 07:30 UTC, sylvainschmitt commented
@EduardoArle , @gepinillab , @hannahlowens , @sgvignali, @codelab3 , @adamlilith, @MayaGueguen, @danlwarren , @AMBarbosa , @AndreaSanchezTapia , I'm still searching for a second reviewer to help Jamie. As this is not my packages I unfortunately did not described every fields, so this a bit more work as usual. But as  `rgbif` and `dismo` are very known packages I hope it will be easy for some of you.

2023-05-11 07:38 UTC, jamiemkass commented on inst/extdata/packages/dismo.yaml
> +occ_acquisition: no
dismo has a `gbif` function that qualifies as occ_acquisition.

2023-05-11 07:39 UTC, jamiemkass commented on inst/extdata/packages/dismo.yaml
> +bias: no
The `ssb` function address sampling bias.

2023-05-11 07:41 UTC, jamiemkass commented on inst/extdata/packages/dismo.yaml
> +mod_tuning: no
The `gbm` function does tune BRTs.

2023-05-11 07:42 UTC, jamiemkass commented on inst/extdata/packages/dismo.yaml
> +pred_extrapolation: no
The `mess` function helps to visualize model extrapolation.

2023-05-11 07:43 UTC, jamiemkass commented on inst/extdata/packages/dismo.yaml
> +pred_inspect: no
The `response` function makes marginal response curves.

2023-05-11 07:46 UTC, jamiemkass commented on inst/extdata/packages/rgbif.yaml
> +occ_cleaning: no
It actually does this now: http://cran.nexr.com/web/packages/rgbif/vignettes/issues_vignette.html

2023-05-11 07:51 UTC, jamiemkass requested changes
Some edits to be made.

2023-05-11 07:53 UTC, sylvainschmitt commented
> Some edits to be made.

Thanks! All done.

2023-05-11 07:54 UTC, sylvainschmitt commented
> Some edits to be made.

Can you approve the changes and validate a new review for me to merge?

2023-05-11 07:56 UTC, merged

2023-05-11 09:45 UTC, jamiemkass commented
Sorry, looks like that wasn't necessary? I'll do this next time.

<http://andersonlab.ccny.cuny.edu>


On Thu, May 11, 2023 at 4:54 PM Sylvain SCHMITT ***@***.***>
wrote:

> Some edits to be made.
>
> Can you approve the changes and validate a new review for me to merge?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sylvainschmitt/sdmverse/pull/19#issuecomment-1543510401>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAP6LW4TPSETOUO77B2EPMTXFSLKHANCNFSM6AAAAAAXSYOYY4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>