Adding kuenm, ellipsenm, and grinnell
sylvainschmitt/sdmverse pull request #26
Opened 2023-05-25 22:20 UTC by marlonecobos

kuenm:
- occ_cleaning:  exploring records outside layer borders included
- env_collinearity: PCA analyses implemented
- backg_sample: options to sample background included
- data_partitioning: option for partitioning data
- mod_fit: fits maxent models
- mod_tuning: model calibration based on feature classes, regularization multipliers, and sets of variables
- mod_ensemble: multiple selected models are used to create consensus
- mod_evaluate: evaluation of models based on distinct metrics
- pred_general: predictions to other scenarios or areas are possible with functions
- pred_extrapolation: analyses of extrapolation risks using MOP
- pred_inspect: variable importance can be explored
- post-processing: other post-processing (post-modeling) analyses allowed, variability analyses

ellipsenm:
- occ_cleaning: remove NA and duplicates 
- env_collinearity: plots to explore variable correlation, PCA analyses implemented
- bias: thinning and exploring records outside layer borders included
- study_region: options to create calibration areas included
- backg_sample: options to sample background included
- data_partitioning: two options for partitioning data
- mod_fit: fits distinct types of ellipsoids to data
- mod_tuning: model calibration based on ellipsoid type and sets of variables
- mod_evaluate: evaluation of models based on distinct metrics
- pred_general: predictions to other scenarios or areas are possible with functions

grinnell:
- env_collinearity: PCA analyses implemented
- study_region: options to simulate calibration areas are the main focus
- backg_sample: options to sample background included
- mod_fit: fits ellipsoids to data
- pred_general: predictions to other scenarios or areas are possible with functions
- post-processing: dispersal simulations using multiple parameters and inputs are allowed

2023-05-30 05:12 UTC, jamiemkass commented on inst/extdata/packages/ellipsenm.yaml
> +occ_cleaning: yes
Not clear what function "exploring records outside layer borders included" refers to. If it means `to_closest`, I suppose that can qualify as cleaning.

2023-05-30 05:52 UTC, jamiemkass requested changes
Some changes need to be made, but looks good. Please make sure to fix the name, title, etc. for `grinnell`.

2023-05-30 05:52 UTC, jamiemkass commented on inst/extdata/packages/kuenm.yaml
> +occ_cleaning: yes
Not clear what function "exploring records outside layer borders included" refers to. If it means to_closest, I suppose that can qualify as cleaning.

2023-05-30 05:52 UTC, jamiemkass commented on inst/extdata/packages/kuenm.yaml
> +data_partitioning: yes
Which function does this? I couldn't find it.

2023-05-30 05:52 UTC, jamiemkass commented on inst/extdata/packages/kuenm.yaml
> +mod_ensemble: yes
I also couldn't find the ensemble function here.

2023-05-30 05:52 UTC, jamiemkass commented on inst/extdata/packages/ellipsenm.yaml
> +bias: yes
Please list the function that does this.

2023-05-30 05:52 UTC, jamiemkass commented on inst/extdata/packages/ellipsenm.yaml
> +post_processing: no
Doesn't this pkg do niche overlap analyses? That should qualify for post-processing.

2023-05-30 05:52 UTC, jamiemkass commented on inst/extdata/packages/grinnell.yaml
> +name: ellipsenm
Please change these fields to those for `grinnell`.

2023-05-30 06:30 UTC, sylvainschmitt commented
Thanks @jamiemkass for the review.

2023-06-01 12:59 UTC, sylvainschmitt commented
@marlonecobos  , your contribution can be integrated without further edits. After merging your pull request, you will be added to the repository contributors. Please expect to be contacted for a review request in the future.

2023-06-01 12:59 UTC, merged